### ISSUE TITLE
almost positive matrices

### ISSUE THREAD

**Issue by tuxette** [pneuvial/adjclust#23]
when the similarity is positive but numerically the last eigenvalues is found negative (~ -1e-15 for instance), the diagonal is modified and a message is thrown to the user: should we prevent this?

**Comment by tuxette** [comment]
unchanged: the message is informative enough to be comprehensible

**Comment by pneuvial** [comment]
The cornercase that was at the origin of this issue was LD values estimated to be slightly >1. With a9f49f4 we force the LD values to be in [0,1].
