### ISSUE TITLE
Useless file src/registerDynamicSymbol.c ?

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/adjclust#24]
Reported by @cambroise and @tuxette : what is the role of the file `src/registerDynamicSymbol.c`?

**Comment by pneuvial** [comment]
If we suppress this file we get a warning at check:

> N  checking compiled code
>    File ‘adjclust/libs/adjclust.so’:
>      Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’
> 
>    It is good practice to register native routines and to disable symbol
>    search.
> 
>    See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
> 

Indeed, quoting TFRM :

> Registering routines has two main advantages: it provides a faster123 way to find the address of the entry point via tables stored in the DLL at compilation time, and it provides a run-time check that the entry point is called with the right number of arguments and, optionally, the right argument types.

**Comment by cambroise** [comment]
Ahh ben dans ce cas laissons le, merci Pierre,
