### ISSUE TITLE
Non-positive 'gains' in adjclust

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/adjclust#3]
Reported by NV2 on Hi-C data.  Also observed in some cases for LD similarity.  Christophe and Guillem say that 'snpStats' sometimes produces LD estimates which are greater than 1. 

* provide a reproducible example using data from the 'snpStats' package 
* add sanity check when performing the clustering

**Comment by pneuvial** [comment]
For the sanity check part, two solutions:

1. before clustering, check that the smallest eigenvalue is non-negative
2. after clustering, make sure that the sequence of 'merges' is increasing

The second option seems much easier to implement because the sequence of merges is readily available after clustering. The first option requires the extraction of the smallest eigenvalue, which is quadratic in the size of the similarity matrix (hence would take longer than performing the entire clustering!)

**Comment by tuxette** [comment]
What would be relevant?
- let the clustering be as it is
- add a warning to the user if the sequence of heights is not increasing
- add an option (default option) in plot to correct spurious (decreasing) branches

**Comment by tuxette** [comment]
chosen policy:
1/ make a reproducible results in which this case happens
2/ print a warning to the user when this happens and create a function to analyze the case
3/ have three types of plots: standard (with reversed branches eventually), corrected (with a minimal correction) and inertia (that displays the - always increasing - intra-inertia)
4/ make a documentation about this point

**Comment by tuxette** [comment]
[1] is made in an external repository (pierre/RLib)

**Comment by tuxette** [comment]
[2] OK also
- used a message instead of a warning (otherwise, problems with the tests)
- created a function "diagnose" with documentation and plot
