### ISSUE TITLE
Add option to label merges on dendrogram

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/adjclust#31]
Goal: be able to see reversals in small examples

**Comment by pneuvial** [comment]
(example to be added by @Zlamouche )

**Comment by pneuvial** [comment]
Clarification: the goal is to label the nodes using the ordering of the merges.

**Comment by pneuvial** [comment]
see packages `dendextend` and `ape`

**Comment by Zlamouche** [comment]
It is now possible through the logical argument nodeLabel of plot.chac.
