### ISSUE TITLE
hclust/adjClust results comparison

### ISSUE THREAD

**Issue by Zlamouche** [pneuvial/adjclust#34]
It seems that results of hclust and adjClust regarding $height are different in the case of dissimilarity data.

Example in R^2 : 

```
x1=t(c(1/2,sqrt(3)/2))
x2=t(c(-1/2,sqrt(3)/2))
x3=t(c(0,-1))
x4=t(c(2,0))
x5=t(c(2,2))
M=rbind(x1,x2,x3,x4,x5)
D1=dist(M)
D2=as.matrix(D1)

fit <- adjClust(D2, type = "dissimilarity")
fit2 <- hclust(D1,method="ward.D2")
fit3 <- hclust(D1,method="ward.D")

fit$height
fit2$height
fit3$height
```

**Comment by tuxette** [comment]
not check but sure
the results of 
`fit <- adjClust(D2, type = "dissimilarity")`
and 
`fit3 <- hclust(D1^2,method="ward.D")`
are identical, which is the expected behavior.

**Comment by pneuvial** [comment]
Just to confirm on the above example that

```
> adjClust(D2, type = "dissimilarity")$height*2
[1]  1.000000  4.000000  4.642735 10.971626
```

is identical to 

```
> hclust(D1^2,method="ward.D")$height
[1]  1.000000  4.000000  4.642734 10.971625
```

Note that it is also identical to 

```
> hclust(D1,method="ward.D2")$height^2
[1]  1.000000  4.000000  4.642734 10.971625
```

More info in Murtagh, F., & Legendre, P. (2014). Ward’s hierarchical agglomerative clustering method: which algorithms implement Ward’s criterion?. Journal of classification, 31(3), 274-295.
