### ISSUE TITLE
Node labels in plotSim

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/adjclust#36]
Nodes label can be added to a dendrogram by setting `nodeLabel=TRUE` in `plot.chac`. 

Can we add this option to `plotSim` when a dendrogram is provided?

**Comment by tuxette** [comment]
this can be done using `axis = TRUE, naxis = nrow(mat)` in plotSim version of commit 493461fb22dedeb5e6f4d8850f2b4907f6aa6898
