### ISSUE TITLE
Color scale and borders in plotSim heatmaps

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/adjclust#37]
In the heatmaps generated by `plotSim` the most distant pairs of data points are plotted in white, which can make the heatmap look incomplete. This is only a problem for very small examples, e.g.

```
set.seed(0xBEEF)
X <- matrix(rnorm(100), 5, 20)
D <- dist(X)
plotSim(D, type = "dissimilarity")
```

Suggestions

- add a black border to each cell of the heatmap (not sure how to do this using base heatmaps; would be easy with ggplot2)
- change default color scale (`heat.colors` are not my favorite anyways!)

**Comment by tuxette** [comment]
second suggestion addressed starting from commit 9383f3ffa0f9175a0a56c1855a5efae6ab8359b1, where heat.colors has been replace by the default palette of `ggplot2::scale_fill_gradient` (investigate better choices?)
