### ISSUE TITLE
Do we need snpClust.dgCMatrix?

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/adjclust#42]
Matrices of the class `Matrix::dgCMatrix` are not necessarily symmetric.  I do not see any use case of `snpClust` on such matrices: should we drop  `snpClust.dgCMatrix`.

Note: the `snpStat::ld` function does produce matrices of class  `Matrix::dgCMatrix`, but then we can't use these matrices because they are not symmetric.  This is related to #35 where we decided to use `snpStat::ld(..., symmetric = TRUE)` in order to obtain symmetric matrices of class `Matrix::dsCMatrix`.

**Comment by tuxette** [comment]
It would be best to keep `dgCMatrix` in order to handle the symmetrization of the matrix for outputs of snpStat::ld obtained by a user which has not used it.
