### ISSUE TITLE
Fix BioC dependencies in GHA "R-CMD-check"

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/adjclust#48]
The action https://github.com/pneuvial/adjclust/actions/workflows/R-CMD-check.yaml has never been working properly because the package depends on Bioconductor packages, see e.g.:

https://github.com/pneuvial/adjclust/runs/3160303868?check_suite_focus=true#step:9:56

See if this can be fixed using the `biocthis` package: http://www.bioconductor.org/packages/release/bioc/vignettes/biocthis/inst/doc/biocthis_dev_notes.html, i.e. simply via:

```r
biocthis::use_bioc_github_action()
```

**Comment by tuxette** [comment]
deprecated... using something else
