### ISSUE TITLE
plot function

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/adjclust#5]
Currently the output of `adjClust` can only be plotted as a dendrogram, using the fact that this output is of class `hclust`. We should add a function that plots the similarity matrix as a triangular heatmap (+ the dendrogram if desired). 

Such plot functions already exist for specific applications, see:
* `HiTC::mapC` for Hi-C data ([`HiTC` package vignette](http://bioconductor.org/packages/release/bioc/vignettes/HiTC/inst/doc/HiTC.pdf))
*  the [`LDheatmap` package vignette](https://cran.r-project.org/web/packages/LDheatmap/vignettes/LDheatmap.pdf)

Can we have something generic?

**Comment by pneuvial** [comment]
NB: triangular dendrogram with:

```
data("ld.example", package="snpStats")
geno <- ceph.1mb[, -316]  ## drop one SNP leading to one missing LD value
p <- ncol(geno)
ld.ceph <- ld(geno, stats="R.squared", depth=p-1)
fit <- snpClust(geno, h=p-1, stats="R.squared")
plot(as.dendrogram(fit), type="triangle")
```

**Comment by tuxette** [comment]
Closed issue: `plot.chac` has been implemented in the current (S3) version.
