### ISSUE TITLE
When loading package in R, can not find the package sparseMatrixStats

### ISSUE THREAD

**Issue by Ledolter** [pneuvial/adjclust#50]
When loading package in R, can not find the package sparseMatrixStats
I cannot find the package sparseMatrixStats in R

**Comment by tuxette** [comment]
Hi @Ledolter : `sparseMatrixStats` is a Bioconductor package that has to be installed with Bioconductor specific installation functions:
http://www.bioconductor.org/packages/release/bioc/html/sparseMatrixStats.html
More precisely:
```
install.packages("BiocManager")
BiocManager::install("sparseMatrixStats")
```
Directly using `BiocManager::install("adjclust")` should install `adjclust` with all dependencies (whatever their repository of origin) directly.
